### ISSUE TITLE
Fix failing Collections

### ISSUE THREAD

**Issue by justb4** [geopython/demo.pygeoapi.io#39]
Several Collections are failing on `master` latest and possibly in versions. At least:

* Dutch Georef stations (backend WFS URL has changed): https://demo.pygeoapi.io/master/collections/dutch_georef_stations/items
* "Utah" with deegree WFS works on https://demo.pygeoapi.io/master/collections/utah_city_locations but the OGR Provider gives errors on startup and feature fetching: 
`[2023-01-18T14:31:02Z] {/pygeoapi/pygeoapi/provider/ogr.py:811} ERROR - Error Number: 1, Type: Failure, Msg: Error returned by server : HTTP error code : 400 (0)
`
* Large Lakes OGR GeoJSON when fetching any Item: https://demo.pygeoapi.io/master/collections/ogr_geojson_lakes/items/0 
```
[2023-01-18T14:33:17Z] {/usr/lib/python3/dist-packages/flask/app.py:1890} ERROR - Exception on /collections/ogr_geojson_lakes/items/0 [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/pygeoapi/pygeoapi/flask_app.py", line 219, in collection_items
    api_.get_collection_item(request, collection_id, item_id))
  File "/pygeoapi/pygeoapi/api.py", line 195, in inner
    headers, status, content = func(*args, **kwargs)
  File "/pygeoapi/pygeoapi/api.py", line 177, in inner
    return func(cls, req_out, *args[2:])
  File "/pygeoapi/pygeoapi/api.py", line 2216, in get_collection_item
    content = render_j2_template(self.config,
  File "/pygeoapi/pygeoapi/util.py", line 378, in render_j2_template
    return template.render(config=l10n.translate_struct(config, locale_, True),
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/pygeoapi/pygeoapi/templates/collections/items/item.html", line 2, in top-level template code
    {% set ptitle = data['properties'][data['title_field']] or "Item " + data['id'] %}
TypeError: can only concatenate str (not "int") to str
```
* same error: https://demo.pygeoapi.io/master/collections/ogr_gpkg_wales_railway_lines/items/38554
* and https://demo.pygeoapi.io/master/collections/ogr_gpkg_poi/items/251211318

Latter seem more related to a real pygeoapi issue....

**Comment by justb4** [comment]
Indeed latter 3 need to be fixed in pygeoapi template code: see geopython/pygeoapi#1107

**Comment by justb4** [comment]
Think the Utah WFS has strange behaviour:
This works:
https://demo.deegree.org/utah-workspace/services/wfs?SERVICE=WFS&REQUEST=GetCapabilities

But
https://demo.deegree.org/utah-workspace/services/wfs?SERVICE=WFS&REQUEST=DescribeFeatureType
This fails
```
<?xml version='1.0' encoding='UTF-8'?>
--
  | <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="2.0.0">
  | <ows:Exception exceptionCode="OperationNotSupported" locator="request">
  | <ows:ExceptionText>Request type 'DescribeFeatureType' is not supported.</ows:ExceptionText>
  | </ows:Exception>
  | </ows:ExceptionReport>


```
