### ISSUE TITLE
Fix config for changes in pygeoapi PR geopython/pygeoapi#244

### ISSUE THREAD

**Issue by justb4** [geopython/demo.pygeoapi.io#5]
geopython/pygeoapi#244 introduced changes in config. These need to be reflected in the `master` demo.

Now error on get collections:
```
[2019-09-26T06:16:20Z] {/usr/local/lib/python3.7/dist-packages/flask/app.py:1891} ERROR - Exception on /collections [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/pygeoapi/pygeoapi/flask_app.py", line 129, in describe_collections
    request.headers, request.args, name)
  File "/pygeoapi/pygeoapi/api.py", line 78, in inner
    return func(cls, headers_, format_, *args, **kwargs)
  File "/pygeoapi/pygeoapi/api.py", line 300, in describe_collections
    'crs': v['extents']['spatial']['crs']
KeyError: 'crs'

```

**Comment by justb4** [comment]
fixed.
